version: '3.7'


services:
  rest_db:
    image: postgres:15.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  rest:
    build: .
    command: python /usr/src/django_rest_test/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/django_rest_test
    ports:
      - 8000:8000
    depends_on:
      - rest_db
volumes:
  postgres_data:
