# Generated by Django 4.2.3 on 2023-08-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bookmark_type_alter_bookmark_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='ref',
            field=models.CharField(max_length=200, verbose_name='Ссылка на страницу'),
        ),
    ]
