# Generated by Django 4.2.3 on 2023-08-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_bookmark_description_alter_bookmark_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='image',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Картинка превью'),
        ),
    ]
