# Generated by Django 4.2.3 on 2023-08-19 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleUser',
            fields=[
                ('role_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='permission.role')),
            ],
            bases=('permission.role',),
        ),
        migrations.AddField(
            model_name='role',
            name='is_selected_role',
            field=models.BooleanField(default=False, verbose_name='Выбранная роль'),
        ),
    ]
